DROP EXTENSION IF EXISTS citext;

DROP TABLE IF EXISTS project;
DROP TABLE IF EXISTS resource_certification;
DROP TABLE IF EXISTS resource_specialty;
DROP TABLE IF EXISTS resource;
DROP TABLE IF EXISTS location;
DROP TABLE IF EXISTS jobtitle;
DROP TABLE IF EXISTS specialty;
DROP TABLE IF EXISTS workgroup;
DROP TABLE IF EXISTS certification;
DROP TABLE IF EXISTS project_status;